/**
 * Local Test Data API Server
 * 
 * This server runs in the background during Playwright test execution.
 * It parses the data/pooledOrders.csv file generated by seedData.js into memory.
 * Playwright tests hit this server on port 3456 to "pop" an order ID from the queue,
 * guaranteeing that parallel tests never attempt to process the same order.
 */
const http = require('http');
const fs = require('fs');
const path = require('path');

let server;
let orderPool = {};

// Parse a simple CSV file with columns: clientId,orderId
function loadOrdersFromCSV() {
    const csvPath = path.join(__dirname, '..', 'data', 'pooledOrders.csv');
    if (!fs.existsSync(csvPath)) {
        console.log(`[DataServer] No pooledOrders.csv found at ${csvPath}. Pool is empty.`);
        return;
    }
    const content = fs.readFileSync(csvPath, 'utf8');
    const lines = content.split('\n');
    let loadedCount = 0;
    
    for (let i = 1; i < lines.length; i++) { // Skip header assuming row 1 is header
        const line = lines[i].trim();
        if (!line) continue;
        const [clientId, orderId] = line.split(',');
        if (clientId && orderId) {
            if (!orderPool[clientId]) orderPool[clientId] = [];
            orderPool[clientId].push(orderId);
            loadedCount++;
        }
    }
    console.log(`[DataServer] Loaded ${loadedCount} orders from CSV.`);
}

function startServer(port = 3456) {
    loadOrdersFromCSV();
    
    server = http.createServer((req, res) => {
        if (req.url.startsWith('/api/orders/pop')) {
            const urlObj = new URL(req.url, `http://${req.headers.host}`);
            const clientId = urlObj.searchParams.get('client');
            
            res.setHeader('Content-Type', 'application/json');
            
            if (clientId && orderPool[clientId] && orderPool[clientId].length > 0) {
                const orderId = orderPool[clientId].shift();
                console.log(`[DataServer] Popped order ${orderId} for client ${clientId}. (${orderPool[clientId].length} remaining)`);
                res.writeHead(200);
                res.end(JSON.stringify({ orderId }));
            } else {
                res.writeHead(404);
                res.end(JSON.stringify({ error: 'No orders available in pool' }));
            }
        } else {
            res.writeHead(404);
            res.end();
        }
    });

    return new Promise((resolve) => {
        server.listen(port, '127.0.0.1', () => {
            console.log(`[DataServer] Test Data Server running on port ${port}`);
            resolve();
        });
    });
}

function stopServer() {
    return new Promise((resolve) => {
        if (server) {
            server.close(() => {
                console.log('[DataServer] Test Data Server stopped.');
                resolve();
            });
        } else {
            resolve();
        }
    });
}

module.exports = { startServer, stopServer, orderPool };
